apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project for ArgoCD applications
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'